name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # ou outra versão que seu projeto requer

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install --verbose

      - name: Build project
        run: npm run build

      - name: Start project
        run: npm start &

      - name: Cypress run
        uses: cypress-io/github-action@v6
